stages:
  - artifacts
  - build
mvn_artifacts:
    stage: artifacts
    #when: manual
    image: maven
    script:
#    - yum install maven -y
    #- rm -rf target
    #- ls -ltr
    - cd 5.16.0-alpine/activemq-src
    - mvn clean
    - mvn package

    artifacts:
        paths:
            - 5.16.0-alpine/activemq-src/target
    allow_failure: false


docker-build-master:
  # Official docker image.
  image: docker:latest
  when: manual
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd 5.16.0-alpine
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
